<template>
  <div class="container-fluid">
    <section class="row">
      <div class="col-12">
        <div class="text-center m-3">
          <h1>Moon Miner</h1>
        </div>
      </div>
      <div class="col-12 text-center">
        <img @click="mineCheese()" class="img-fluid"
          src="https://images.unsplash.com/photo-1479090793912-eb9929f4fdb2?q=80&w=968&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
          alt="">
        <!-- NOTE {{  }} denotes text interpolating inside of HTML text content -->
        <h2 class="mt-2">Cheese: 🧀{{ cheese }}</h2>
        <!-- NOTE values here will be automatically updated if a reactive property inside of a computed changes -->
        <h2>Click total: {{ clickTotal }} Auto total: {{ autoTotal }}</h2>
      </div>
    </section>

    <section class="row">
      <!-- NOTE generates HTML for each upgrade in our upgrades array -->
      <!-- NOTE clickupgrades is the array we are iterating over from our return object -->
      <!-- NOTE upgrade creates a predicate that is scoped to the HTML you are v-foring over -->
      <!-- NOTE key should be a unique property from each item in the array -->
      <div v-for="upgrade in clickUpgrades" :key="upgrade.name" class="col-md-6 mb-2">
        <div class="bg-info p-4 rounded shadow">
          <h3 class="text-dark text-center">
            <!-- NOTE drill into the upgrade object generated by the v-for-->
            {{ upgrade.name }}
            <!-- NOTE reference types (objects, arrays) can be passed down as arguments from your HTML -->
            <!-- NOTE disabled attribute is conditionally applied -->
            <button @click="purchaseUpgrade(upgrade)" :disabled="cheese < upgrade.price" class="btn btn-primary">
              <!-- NOTE :class is an example of attribute binding. Each object has it's own icon, and it's applied as the class here -->
              <i class="mdi" :class="upgrade.icon"></i>
              Buy Upgrade
            </button>
          </h3>
          <h4 class="text-dark text-center">
            {{ upgrade.price }} cheese | {{ upgrade.quantity }} qty | +{{ upgrade.multiplier }} cheese per click
          </h4>
        </div>
      </div>

      <!-- NOTE upgrade variable here is scoped to this HTML, has no relation to the above variable from clickUpgrades v-for -->
      <div v-for="upgrade in autoUpgrades" :key="upgrade.name" class="col-md-6 mb-2">
        <div class="bg-warning p-4 rounded shadow">
          <h3 class="text-dark text-center">
            {{ upgrade.name }}
            <button @click="purchaseUpgrade(upgrade)" :disabled="cheese < upgrade.price" class="btn btn-primary">
              <i class="mdi" :class="upgrade.icon"></i>
              Buy
              Upgrade</button>
          </h3>
          <h4 class="text-dark text-center">
            {{ upgrade.price }} cheese | {{ upgrade.quantity }} qty | +{{ upgrade.multiplier }} cheese per 3 seconds
          </h4>
        </div>
      </div>
    </section>


  </div>
</template>

<script>
import { computed, onMounted, ref } from 'vue';
import { AppState } from '../AppState.js'
import { cheeseService } from '../services/CheeseService.js'
import { upgradesService } from '../services/UpgradesService.js'
export default {

  setup() {
    // NOTE private
    // const cheese = ref(0)

    // NOTE _collectAuto cannot be called from the HTML because it is not inside of our return object
    function _collectAuto() {
      cheeseService.collectAuto()
    }

    // NOTE onMounted is a lifecycle hook that will fire off whenever this vue component is mounted into the view (DOM). Since this a page component, it fires off whenever the page loads (similar to constructor inside of Controllers)
    onMounted(() => {
      setInterval(_collectAuto, 3000)
    })



    return {
      // NOTE public
      // cheese: computed(() => { return AppState.cheese }), // explicit return
      // NOTE computed allows us to bring in properties from a watchable Vue object (ref, reactive). Whenever a value changes within a watchable object, the computed function will re-run, giving us reactivity
      cheese: computed(() => AppState.cheese), // implied return
      clickUpgrades: computed(() => AppState.clickUpgrades),
      autoUpgrades: computed(() => AppState.autoUpgrades),
      // NOTE computed's can take in functions with multiple lines, but should always return a value
      clickTotal: computed(() => {
        let clickTotal = upgradesService.generateUpgradeTotal(AppState.clickUpgrades)
        clickTotal++
        return clickTotal
      }),
      autoTotal: computed(() => {
        let autoTotal = upgradesService.generateUpgradeTotal(AppState.autoUpgrades)
        return autoTotal
      }),


      // NOTE a method defined within the return object is callable by the HTML template
      mineCheese() {
        // NOTE changes data should still be handled by service
        // cheese.value++
        cheeseService.mineCheese()
      },

      purchaseUpgrade(upgradeToPurchase) {
        console.log('purchasing upgrade', upgradeToPurchase);

        upgradesService.purchaseUpgrade(upgradeToPurchase)

      }
    }
  }
}
</script>

<!-- NOTE scoped attribute only applies styles to this vue file (component) -->
<style scoped lang="scss">
// NOTE this element selector only applies to the img tag in this component
img {
  height: 40vh;
  width: 40vh;
  border-radius: 50%;
  object-fit: cover;
}
</style>
